server {
    listen 80;
    server_name _;

    keepalive_timeout 30; # time in seconds
    keepalive_requests 100; # max number of requests per connection

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html =404;
    }
}
